layout_spectrum: 0.9749104
color:
  saturation: 0.8458781
  lightness: 0.7473118
  brandStrength: 1
  brandColors:
    - '#17171D'
    - '#B4B699'
    - '#FACEC7'
    - '#A49065'
    - '#FCFCFB'
  rhythmicContrast: 0.6397849
typography_spectrum: 0.327957
name: Martin Källström
